### ISSUE TITLE
Frosted Glass Light Gray Brown is too dark in  1.15.2

### ISSUE THREAD

**Issue by FraukeS** [Ommina/WallpaperCraft#6]
The block for Frosted Glass Light Gray Brown is much darker than the other patterns in this colour and also much darker than the Frosted Glass Gray Brown block next to it.
![2020-08-07_23 58 55](https://user-images.githubusercontent.com/24796332/89692024-ce2a4b00-d90a-11ea-802d-10a5c171c758.png)

**Comment by Ommina** [comment]
I'm going to have to really think about this one for a bit.

On the one hand, you're totally correct, the colour of that particular block is somewhat out of place.  On the other hand, it's been like that since 1.7.10, as best I can tell.

Of course, that alone isn't sufficient reason to leave it unchanged.

But I am significantly bothered by fact that changing the texture would change people's builds, and I'm not sure that's a step I want to take. Hm.

**Comment by Ommina** [comment]
OK, after watching a video of a build made with goodness known how many Wallpapercraft blocks, I can't bring myself to change the palette, however much I agree with you that the particular shade is out of place.

If I ever reach the point where I have to release a breaking version, I can look at changing it then, but for now, I feel it would mess with user's creations.
